# Generated by Django 4.0 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_created=True)),
                ('Product', models.CharField(default='', max_length=50)),
                ('Order_by', models.CharField(default='', max_length=50)),
                ('amnt', models.IntegerField(default=0)),
                ('order_status', models.CharField(default='progress', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_created=True)),
                ('Product', models.CharField(default='', max_length=50)),
                ('product_detials', models.CharField(default='', max_length=250)),
                ('qnt', models.IntegerField(default=0)),
                ('amnt', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
