# Generated by Django 4.0 on 2023-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_loss_remove_user_profit_stock_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='profit',
        ),
        migrations.AddField(
            model_name='user',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
